### PR TITLE
First trial of brute force alg

### PR DESCRIPTION
**Pull request by ludusrusso**

### CODE REVIEW

**Comment by gmacario** [comment]
@ludusrusso I will review as soon as #35 is resolved

**Comment by gmacario** [comment]
In parallel I will suggest that @xrmx and @FiorellaSibona shall have a look at the actual code (which I do not understand since I am a Python-newbie)

**Review by xrmx — APPROVED** [review]

**Comment by gmacario** [comment]
PR-34 builds successfully:

image

**Review by gmacario — APPROVED** [review]

**Comment by gmacario** [comment]
@FiorellaSibona waiting for your review before merging

**Comment by gmacario** [comment]
@fiorella_sibona Ping!

**Comment by gmacario** [comment]
2 approvers out of 3, @FiorellaSibona has not replied for two days, merging

**Pull request merged**
